### ISSUE TITLE
Category reshuffling coming to Battle for Azeroth + new release?

### ISSUE THREAD

**Issue by flatluigi** [DeeRez/achieveit#2]
[Wowhead's articles on new Alpha changes](https://www.wowhead.com/news=283428/battle-for-azeroth-ui-updates-expansion-features-achievements-category) include a new category and reshuffling of old achievements that might require more updates to this.

Once that goes live, it might be worth it to release your update as a new addon on Curse, as it's currently over four years since both the last update to the original addon and the original author's last login to the website. I think at this point the sum total of your changes adds up to an original addon that wouldn't cause any conflicts on upload.

**Comment by DeeRez** [comment]
I know this is a very late reply, but I stopped checking this repo after MuffinManKen took over ownership of the addon. I've just been assigned as a maintainer for the addon, so there will be updates pushed to Curse when I feel they are ready.
