### ISSUE TITLE
Achievement in wrong location

### ISSUE THREAD

**Issue by gizzmo** [DeeRez/achieveit#8]
Under Profession>Archaeology, the achievement [[Collector: Carved Bronze Mirrors]](https://www.wowhead.com/achievement=7343/collector-carved-bronze-mirrors) is sorted into Mantid, when it's a Pandaren artifact.

https://www.wowhead.com/spell=113975/carved-bronze-mirror

**Comment by DeeRez** [comment]
Fixed in v9.2.0.02
